"""
Django settings for server_api project.

Generated by 'django-admin startproject' using Django 2.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""
CONF_FILE = '/.gf_conf'

import os
from .base import *
from utils.common import gf_conf

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': '127.0.0.1',
        'NAME': 'justdoit',
        'USER': 'root',
        'PASSWORD': gf_conf.get_value('app_mysql_pwd'),
        # 'PASSWORD': "",
        'OPTIONS': {'charset': 'utf8mb4'},
        'CONN_MAX_AGE': 80000
    }
}
